name: CI

# This runs every time a new commit is pushed to GitHub.
#
# You can even use the following syntax:
# push:
#     branches: [main]
#   pull_request:
#     branches: [main]
# and declare branches and patterns
#
on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    # We run our `rspec` tests on many versions of Ruby to ensure compatibility.
    strategy:
      matrix:
        ruby-version: ["2.6", "2.7", "3.0"]
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "RSpec tests: Ruby ${{ matrix.ruby-version }}"
    steps:
      # This is an action from the public marketplace. We reference a specific commit as a security measure,
      # but there are many ways to reference an action:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run tests
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@8230315d06ad95c617244d2f265d237a1682d445
      - name: Set up Ruby
        uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          bundler-cache: true
          ruby-version: head
      - name: Run style checks
        run: bundle exec rubocop
